services:
  backoffice:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://api:3000
    environment:
      - NODE_ENV=production
      - PORT=80
    networks:
      - tumaa_network
    restart: unless-stopped

networks:
  tumaa_network:
    external: true
    name: tumaa_network
